### ISSUE TITLE
Guessing Number: Move the logic in the main to a lib

### ISSUE THREAD

**Issue by lucaspere** [lucaspere/rust_projects#1]
## Why?
Currently the entire logic is inside the ``main`` function. It's necessary to create a ``lib`` for it that allow us to create integration tests for it.

## Tasks:
1. [x] - Move the logic to a lib.
2. [ ] - Create integration tests for the package.
3. [x] - Completes the unit tests.

## Useful links:
- https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html;
- https://zerotomastery.io/blog/complete-guide-to-testing-code-in-rust/
- https://doc.rust-lang.org/book/ch11-03-test-organization.html
